---

- name: ssh-keys
  copy:
    src: ~/ssh-keys/
    dest: ~/ssh-keys
    mode: u=rw,g=,o=

- name: ssh auto config
  template:
    src: ssh.config.j2
    dest: ~/.ssh/config.auto

- name: include ssh auto config
  lineinfile:
    path: ~/.ssh/config
    line: Include config.auto
    insertbefore: BOF
    create: true

- name: enable and start ssh-agent user service
  systemd:
    name: ssh-agent.service
    state: started
    enabled: true
    user: true
  when: home_eralitex_vdesk_started_and_enabled
