desktop_packages:
  # audio
  - audacity
  - sound-juicer
  - pulseaudio
  - pavucontrol
  - pasystray

  # applications
  - eog
  - evince
  - catfish
  - xfce4-screenshooter

  # authentication, keys and passwords
  - seahorse
  - ssh-askpass-gnome

  # bluetooth
  - bluetooth
  - blueman

  # editors
  - geany
  - geany-plugins

  # filesystem
  - gvfs
  - gvfs-backends
  - gvfs-fuse
  - zip
  - unzip
  - baobab
  - thunar
  - thunar-archive-plugin
  - catfish
  - unison-gtk
  - xarchiver

  # fonts
  - fonts-recommended
  - fonts-font-awesome
  - fonts-symbola
  - fonts-noto-color-emoji
  - fonts-firacode
  - fonts-hack
  - fonts-inconsolata
  - fonts-terminus
  - fonts-opendyslexic

  # graphics
  - gimp
  - gimp-help-de
  - inkscape
  - gthumb
  - krita
  - krita-l10n
  - eog
  - xfce4-screenshooter

  # mail
  - thunderbird
  - thunderbird-l10n-de
  - hunspell-de-de
  - evolution
  - evolution-ews

  # mindmap
  - vym

  # multimedia
  - vlc
  - vlc-l10n
  #- libdvd-pkg
  - brasero

  # notifications
  - notify-osd

  # office
  - evince
  # see libreoffice_packages

  # remote desktop tools
  - tigervnc-common
  - tigervnc-scraping-server
  - tigervnc-standalone-server
  - tigervnc-viewer
  - tigervnc-xorg-extension
  - ssvnc
  - socat

  # scanner
  - simple-scan
  - gscan2pdf
  - xsane

  # tools
  - redshift-gtk
  - barrier
  - xinput
  - rofi
  - xclip
  - arandr
  - xbindkeys
  - xdotool
  - xplanet
  - xkbset
  - numlockx
  - unclutter
  - x11-utils
  - feh
  - sm
  - xloadimage

  # web
  - firefox-esr
  - firefox-esr-l10n-de
  - chromium
  - chromium-l10n
  - webext-ublock-origin-firefox
  - webext-ublock-origin-chromium

  # lockscreen
  - mate-screensaver
  - xscreensaver-gl
  - python3
  - mate-power-manager
  - xautolock
  - xss-lock
  - xbacklight
  - i3lock
  - xssproxy
  - xsecurelock

  # xfce
  - xfce4
  - xfce4-goodies
  - xfce4-whiskermenu-plugin
  - xfce4-smartbookmark-plugin
  - xfce4-places-plugin
  - xfce4-datetime-plugin
  - xfce4-power-manager

  # printer
  - system-config-printer

  # i3
  - i3-wm
  - i3blocks
  - i3status
  - i3pystatus

  # themes
  - dmz-cursor-theme
  - gnome-brave-icon-theme

  # terminal emulators
  - xfce4-terminal
  - kitty

  # drive management
  - gparted
  - gnome-disk-utility
